# 📊 Financial Tools

📚 *Based on the book "**Machine Learning & Data Science Blueprints for Finance**", by Hariom Tatsat, Sahil Puri and Brad Lookabaugh (from page 181 to 184)*

Financial tools are able to extract some analytical and probabilistic mathematical features from the base dataset. The purpose is to get a better view from the raw data. It's basically some mathematical tools to allow us to see beyond the surface of the dataset and get us to analyse the timeseries more accuratelly.

## 1. ```import sys``` (getting the libraries in the right enviroment

The comand ```import sys``` guarantee that ```pandas``` and ```numpy``` is installed in the right enviroment: here.

In [1]:
import sys
!{sys.executable} -m pip install pandas numpy

Requirement already satisfied: pandas in c:\users\miguel\appdata\local\programs\python\python313\lib\site-packages (2.3.3)
Requirement already satisfied: numpy in c:\users\miguel\appdata\local\programs\python\python313\lib\site-packages (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\miguel\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\miguel\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\miguel\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\miguel\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Now we import ```pandas``` and ```numpy```

In [2]:
import pandas as pd
import numpy as np

## 2. Loading data

Data should be loaded from 'Libellula/data/rawEURUSD1.csv':

In [3]:
data = pd.read_csv('C:/projects/Libellula/data/raw/EUR_USD.csv')
data = (
    data.assign(_timestamp=pd.to_datetime(data['Date'], format='%m/%d/%Y'))
    .sort_values('_timestamp')
    .drop(columns='_timestamp')
    .reset_index(drop=True)
)
data

            Date   Price    Open    High     Low  Vol. Change %
0     02/11/2020  1.0914  1.0911  1.0926  1.0890   NaN    0.05%
1     02/12/2020  1.0871  1.0916  1.0926  1.0865   NaN   -0.39%
2     02/13/2020  1.0840  1.0874  1.0890  1.0833   NaN   -0.29%
3     02/14/2020  1.0830  1.0841  1.0862  1.0827   NaN   -0.09%
4     02/17/2020  1.0834  1.0832  1.0852  1.0821   NaN    0.04%
...          ...     ...     ...     ...     ...   ...      ...
1563  02/06/2026  1.1817  1.1778  1.1827  1.1765   NaN    0.34%
1564  02/08/2026  1.1827  1.1814  1.1828  1.1810   NaN    0.08%
1565  02/09/2026  1.1915  1.1817  1.1927  1.1809   NaN    0.74%
1566  02/10/2026  1.1895  1.1913  1.1929  1.1887   NaN   -0.17%
1567  02/11/2026  1.1871  1.1895  1.1928  1.1833   NaN   -0.20%

[1568 rows x 7 columns]

### 2.1. Data cleaning

Now we get away with the 'Not a Number' data

In [4]:
data = data.dropna(axis=1)
data

            Date   Price    Open    High     Low Change %
0     02/11/2020  1.0914  1.0911  1.0926  1.0890    0.05%
1     02/12/2020  1.0871  1.0916  1.0926  1.0865   -0.39%
2     02/13/2020  1.0840  1.0874  1.0890  1.0833   -0.29%
3     02/14/2020  1.0830  1.0841  1.0862  1.0827   -0.09%
4     02/17/2020  1.0834  1.0832  1.0852  1.0821    0.04%
...          ...     ...     ...     ...     ...      ...
1563  02/06/2026  1.1817  1.1778  1.1827  1.1765    0.34%
1564  02/08/2026  1.1827  1.1814  1.1828  1.1810    0.08%
1565  02/09/2026  1.1915  1.1817  1.1927  1.1809    0.74%
1566  02/10/2026  1.1895  1.1913  1.1929  1.1887   -0.17%
1567  02/11/2026  1.1871  1.1895  1.1928  1.1833   -0.20%

[1568 rows x 6 columns]

## 3. Financial Tools

### 3.1. Moving averages

#### 3.1.1. Short moving average

In [5]:
# Create short simple moving average over the short window
data['short_mavg'] = data['Price'].rolling(window=10, min_periods=1,center=False).mean()
data

            Date   Price    Open    High     Low Change %  short_mavg
0     02/11/2020  1.0914  1.0911  1.0926  1.0890    0.05%    1.091400
1     02/12/2020  1.0871  1.0916  1.0926  1.0865   -0.39%    1.089250
2     02/13/2020  1.0840  1.0874  1.0890  1.0833   -0.29%    1.087500
3     02/14/2020  1.0830  1.0841  1.0862  1.0827   -0.09%    1.086375
4     02/17/2020  1.0834  1.0832  1.0852  1.0821    0.04%    1.085780
...          ...     ...     ...     ...     ...      ...         ...
1563  02/06/2026  1.1817  1.1778  1.1827  1.1765    0.34%    1.187080
1564  02/08/2026  1.1827  1.1814  1.1828  1.1810    0.08%    1.186540
1565  02/09/2026  1.1915  1.1817  1.1927  1.1809    0.74%    1.185280
1566  02/10/2026  1.1895  1.1913  1.1929  1.1887   -0.17%    1.184690
1567  02/11/2026  1.1871  1.1895  1.1928  1.1833   -0.20%    1.183690

[1568 rows x 7 columns]

#### 3.1.2. Long moving average

In [6]:
# Create long simple moving average over the long window
data['long_mavg'] = data['Price'].rolling(window=60, min_periods=1, center=False).mean()
data

,Date,Price,Open,High,Low,Change %,short_mavg,long_mavg
0,02/11/2020,1.0914,1.0911,1.0926,1.0890,0.05%,1.091400,1.091400
1,02/12/2020,1.0871,1.0916,1.0926,1.0865,-0.39%,1.089250,1.089250
2,02/13/2020,1.0840,1.0874,1.0890,1.0833,-0.29%,1.087500,1.087500
3,02/14/2020,1.0830,1.0841,1.0862,1.0827,-0.09%,1.086375,1.086375
4,02/17/2020,1.0834,1.0832,1.0852,1.0821,0.04%,1.085780,1.085780
...,...,...,...,...,...,...,...,...
1563,02/06/2026,1.1817,1.1778,1.1827,1.1765,0.34%,1.187080,1.170733
1564,02/08/2026,1.1827,1.1814,1.1828,1.1810,0.08%,1.186540,1.171127
1565,02/09/2026,1.1915,1.1817,1.1927,1.1809,0.74%,1.185280,1.171683
1566,02/10/2026,1.1895,1.1913,1.1929,1.1887,-0.17%,1.184690,1.172278
1567,02/11/2026,1.1871,1.1895,1.1928,1.1833,-0.20%,1.183690,1.172848

#### 3.1.3. Creating a signal

Now we create a signal based on the crossing of a moving average over the other one. In this case, when the short moving average is higher than the long one, we have a positive value equals to one.

In [7]:
# Create signals
data['signal'] = np.where(data['short_mavg'] > data['long_mavg'], 1.0, 0.0)
data

,Date,Price,Open,High,Low,Change %,short_mavg,long_mavg,signal
0,02/11/2020,1.0914,1.0911,1.0926,1.0890,0.05%,1.091400,1.091400,0.0
1,02/12/2020,1.0871,1.0916,1.0926,1.0865,-0.39%,1.089250,1.089250,0.0
2,02/13/2020,1.0840,1.0874,1.0890,1.0833,-0.29%,1.087500,1.087500,0.0
3,02/14/2020,1.0830,1.0841,1.0862,1.0827,-0.09%,1.086375,1.086375,0.0
4,02/17/2020,1.0834,1.0832,1.0852,1.0821,0.04%,1.085780,1.085780,0.0
...,...,...,...,...,...,...,...,...,...
1563,02/06/2026,1.1817,1.1778,1.1827,1.1765,0.34%,1.187080,1.170733,1.0
1564,02/08/2026,1.1827,1.1814,1.1828,1.1810,0.08%,1.186540,1.171127,1.0
1565,02/09/2026,1.1915,1.1817,1.1927,1.1809,0.74%,1.185280,1.171683,1.0
1566,02/10/2026,1.1895,1.1913,1.1929,1.1887,-0.17%,1.184690,1.172278,1.0
1567,02/11/2026,1.1871,1.1895,1.1928,1.1833,-0.20%,1.183690,1.172848,1.0

#### 3.1.4. Exponenttial moving average

In [8]:
#calculation of exponential moving average
def EMA(data, n):
    EMA = pd.Series(data['Price'].ewm(span=n, min_periods=n).mean(), name='EMA_' + str(n))
    return EMA
data['EMA10'] = EMA(data, 10)
data['EMA30'] = EMA(data, 30)
data['EMA200'] = EMA(data, 200)
data

,Date,Price,Open,High,Low,Change %,short_mavg,long_mavg,signal,EMA10,EMA30,EMA200
0,02/11/2020,1.0914,1.0911,1.0926,1.0890,0.05%,1.091400,1.091400,0.0,NaN,NaN,NaN
1,02/12/2020,1.0871,1.0916,1.0926,1.0865,-0.39%,1.089250,1.089250,0.0,NaN,NaN,NaN
2,02/13/2020,1.0840,1.0874,1.0890,1.0833,-0.29%,1.087500,1.087500,0.0,NaN,NaN,NaN
3,02/14/2020,1.0830,1.0841,1.0862,1.0827,-0.09%,1.086375,1.086375,0.0,NaN,NaN,NaN
4,02/17/2020,1.0834,1.0832,1.0852,1.0821,0.04%,1.085780,1.085780,0.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1563,02/06/2026,1.1817,1.1778,1.1827,1.1765,0.34%,1.187080,1.170733,1.0,1.182032,1.177400,1.155124
1564,02/08/2026,1.1827,1.1814,1.1828,1.1810,0.08%,1.186540,1.171127,1.0,1.182153,1.177742,1.155399
1565,02/09/2026,1.1915,1.1817,1.1927,1.1809,0.74%,1.185280,1.171683,1.0,1.183853,1.178630,1.155758
1566,02/10/2026,1.1895,1.1913,1.1929,1.1887,-0.17%,1.184690,1.172278,1.0,1.184880,1.179331,1.156094
1567,02/11/2026,1.1871,1.1895,1.1928,1.1833,-0.20%,1.183690,1.172848,1.0,1.185283,1.179832,1.156402

### 3.2. Rate of change

In [9]:
def ROC(data, n):
    M = data.diff(n - 1)
    N = data.shift(n - 1)
    ROC = pd.Series(((M / N) * 100), name = 'ROC_' + str(n))
    return ROC
data['ROC10'] = ROC(data['Price'], 10)
data['ROC30'] = ROC(data['Price'], 30)
data

,Date,Price,Open,High,Low,Change %,short_mavg,long_mavg,signal,EMA10,EMA30,EMA200,ROC10,ROC30
0,02/11/2020,1.0914,1.0911,1.0926,1.0890,0.05%,1.091400,1.091400,0.0,NaN,NaN,NaN,NaN,NaN
1,02/12/2020,1.0871,1.0916,1.0926,1.0865,-0.39%,1.089250,1.089250,0.0,NaN,NaN,NaN,NaN,NaN
2,02/13/2020,1.0840,1.0874,1.0890,1.0833,-0.29%,1.087500,1.087500,0.0,NaN,NaN,NaN,NaN,NaN
3,02/14/2020,1.0830,1.0841,1.0862,1.0827,-0.09%,1.086375,1.086375,0.0,NaN,NaN,NaN,NaN,NaN
4,02/17/2020,1.0834,1.0832,1.0852,1.0821,0.04%,1.085780,1.085780,0.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1563,02/06/2026,1.1817,1.1778,1.1827,1.1765,0.34%,1.187080,1.170733,1.0,1.182032,1.177400,1.155124,-0.538675,0.382263
1564,02/08/2026,1.1827,1.1814,1.1828,1.1810,0.08%,1.186540,1.171127,1.0,1.182153,1.177742,1.155399,-1.777261,0.672455
1565,02/09/2026,1.1915,1.1817,1.1927,1.1809,0.74%,1.185280,1.171683,1.0,1.183853,1.178630,1.155758,-0.326251,1.438788
1566,02/10/2026,1.1895,1.1913,1.1929,1.1887,-0.17%,1.184690,1.172278,1.0,1.184880,1.179331,1.156094,-0.634868,1.268517
1567,02/11/2026,1.1871,1.1895,1.1928,1.1833,-0.20%,1.183690,1.172848,1.0,1.185283,1.179832,1.156402,0.177215,1.288396

### 4. Momentum

In [10]:
def MOM(data, n):
    MOM = pd.Series(data.diff(n), name='Momentum_' + str(n))
    return MOM
data['MOM10'] = MOM(data['Price'], 10)
data['MOM30'] = MOM(data['Price'], 30)
data

,Date,Price,Open,High,Low,Change %,short_mavg,long_mavg,signal,EMA10,EMA30,EMA200,ROC10,ROC30,MOM10,MOM30
0,02/11/2020,1.0914,1.0911,1.0926,1.0890,0.05%,1.091400,1.091400,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,02/12/2020,1.0871,1.0916,1.0926,1.0865,-0.39%,1.089250,1.089250,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,02/13/2020,1.0840,1.0874,1.0890,1.0833,-0.29%,1.087500,1.087500,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,02/14/2020,1.0830,1.0841,1.0862,1.0827,-0.09%,1.086375,1.086375,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,02/17/2020,1.0834,1.0832,1.0852,1.0821,0.04%,1.085780,1.085780,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1563,02/06/2026,1.1817,1.1778,1.1827,1.1765,0.34%,1.187080,1.170733,1.0,1.182032,1.177400,1.155124,-0.538675,0.382263,-0.0011,0.0045
1564,02/08/2026,1.1827,1.1814,1.1828,1.1810,0.08%,1.186540,1.171127,1.0,1.182153,1.177742,1.155399,-1.777261,0.672455,-0.0054,0.0055
1565,02/09/2026,1.1915,1.1817,1.1927,1.1809,0.74%,1.185280,1.171683,1.0,1.183853,1.178630,1.155758,-0.326251,1.438788,-0.0126,0.0167
1566,02/10/2026,1.1895,1.1913,1.1929,1.1887,-0.17%,1.184690,1.172278,1.0,1.184880,1.179331,1.156094,-0.634868,1.268517,-0.0059,0.0149
1567,02/11/2026,1.1871,1.1895,1.1928,1.1833,-0.20%,1.183690,1.172848,1.0,1.185283,1.179832,1.156402,0.177215,1.288396,-0.0100,0.0125

### 5. RSI (Relative Index Strength)

In [11]:
def RSI(series, period):
    delta = series.diff().dropna()
    u = delta * 0
    d = u.copy()
    u[delta > 0] = delta[delta > 0]
    d[delta < 0] = -delta[delta < 0]
    u[u.index[period-1]] = np.mean( u[:period] ) #first value is sum of avg gains
    u = u.drop(u.index[:(period-1)])
    d[d.index[period-1]] = np.mean( d[:period] ) #first value is sum of avg losses
    d = d.drop(d.index[:(period-1)])
    rs = u.ewm(com=period-1, adjust=False).mean() / d.ewm(com=period-1, adjust=False).mean()
    return 100 - 100 / (1 + rs)
data['RSI10'] = RSI(data['Price'], 10)
data['RSI30'] = RSI(data['Price'], 30)
data['RSI200'] = RSI(data['Price'], 200)
data

,Date,Price,Open,High,Low,Change %,short_mavg,long_mavg,signal,EMA10,EMA30,EMA200,ROC10,ROC30,MOM10,MOM30,RSI10,RSI30,RSI200
0,02/11/2020,1.0914,1.0911,1.0926,1.0890,0.05%,1.091400,1.091400,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,02/12/2020,1.0871,1.0916,1.0926,1.0865,-0.39%,1.089250,1.089250,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,02/13/2020,1.0840,1.0874,1.0890,1.0833,-0.29%,1.087500,1.087500,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,02/14/2020,1.0830,1.0841,1.0862,1.0827,-0.09%,1.086375,1.086375,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,02/17/2020,1.0834,1.0832,1.0852,1.0821,0.04%,1.085780,1.085780,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1563,02/06/2026,1.1817,1.1778,1.1827,1.1765,0.34%,1.187080,1.170733,1.0,1.182032,1.177400,1.155124,-0.538675,0.382263,-0.0011,0.0045,52.126864,54.071043,53.289615
1564,02/08/2026,1.1827,1.1814,1.1828,1.1810,0.08%,1.186540,1.171127,1.0,1.182153,1.177742,1.155399,-1.777261,0.672455,-0.0054,0.0055,53.224147,54.503905,53.352779
1565,02/09/2026,1.1915,1.1817,1.1927,1.1809,0.74%,1.185280,1.171683,1.0,1.183853,1.178630,1.155758,-0.326251,1.438788,-0.0126,0.0167,61.787958,58.098868,53.904069
1566,02/10/2026,1.1895,1.1913,1.1929,1.1887,-0.17%,1.184690,1.172278,1.0,1.184880,1.179331,1.156094,-0.634868,1.268517,-0.0059,0.0149,59.057562,57.039213,53.758948
1567,02/11/2026,1.1871,1.1895,1.1928,1.1833,-0.20%,1.183690,1.172848,1.0,1.185283,1.179832,1.156402,0.177215,1.288396,-0.0100,0.0125,55.771520,55.776364,53.584964

### 6. Stochastic oscillators

That one is one of the most important for the purposes of our risk management model. 

> "A stochastic oscillator is a momentum indicator that compares the closing price of a security to a range of its previous prices over a certain period of time. %K and %D are slow and fast indicators. The fast indicator is more sensitive than the slow indicator to changes in the price of the underlying security and will likely result in many transaction signals."
>> ***Machine Learning & Data Science Blueprints for Finance*** (p. 182)

In [12]:
def STOK(close, low, high, n):
    STOK = ((close - low.rolling(n).min()) / (high.rolling(n).max() - low.rolling(n).min())) * 100
    return STOK
    
def STOD(close, low, high, n):
    STOK = ((close - low.rolling(n).min()) / (high.rolling(n).max() - low.rolling(n).min())) * 100
    STOD = STOK.rolling(3).mean()
    return STOD

data['%K10'] = STOK(data['Price'], data['Low'], data['High'], 10)
data['%D10'] = STOD(data['Price'], data['Low'], data['High'], 10)
data['%K30'] = STOK(data['Price'], data['Low'], data['High'], 30)
data['%D30'] = STOD(data['Price'], data['Low'], data['High'], 30)
data['%K200'] = STOK(data['Price'], data['Low'], data['High'], 200)
data['%D200'] = STOD(data['Price'], data['Low'], data['High'], 200)

data

,Date,Price,Open,High,Low,Change %,short_mavg,long_mavg,signal,EMA10,...,MOM30,RSI10,RSI30,RSI200,%K10,%D10,%K30,%D30,%K200,%D200
0,02/11/2020,1.0914,1.0911,1.0926,1.0890,0.05%,1.091400,1.091400,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,02/12/2020,1.0871,1.0916,1.0926,1.0865,-0.39%,1.089250,1.089250,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,02/13/2020,1.0840,1.0874,1.0890,1.0833,-0.29%,1.087500,1.087500,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,02/14/2020,1.0830,1.0841,1.0862,1.0827,-0.09%,1.086375,1.086375,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,02/17/2020,1.0834,1.0832,1.0852,1.0821,0.04%,1.085780,1.085780,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1563,02/06/2026,1.1817,1.1778,1.1827,1.1765,0.34%,1.187080,1.170733,1.0,1.182032,...,0.0045,52.126864,54.071043,53.289615,16.560510,21.338985,48.323471,45.036160,74.161736,72.518080
1564,02/08/2026,1.1827,1.1814,1.1828,1.1810,0.08%,1.186540,1.171127,1.0,1.182153,...,0.0055,53.224147,54.503905,53.352779,19.745223,16.755282,50.295858,46.351085,75.147929,73.175542
1565,02/09/2026,1.1915,1.1817,1.1927,1.1809,0.74%,1.185280,1.171683,1.0,1.183853,...,0.0167,61.787958,58.098868,53.904069,53.380783,29.895505,67.652860,55.424063,83.826430,77.712032
1566,02/10/2026,1.1895,1.1913,1.1929,1.1887,-0.17%,1.184690,1.172278,1.0,1.184880,...,0.0149,59.057562,57.039213,53.758948,56.034483,43.053496,63.708087,60.552268,81.854043,80.276134
1567,02/11/2026,1.1871,1.1895,1.1928,1.1833,-0.20%,1.183690,1.172848,1.0,1.185283,...,0.0125,55.771520,55.776364,53.584964,50.236967,53.217411,58.974359,63.445102,79.487179,81.722551

### Saving new dataset with the financial tools

In [13]:
data.to_csv("C:/projects/Libellula/data/processed/financial_tools_datset.csv", index=False)